### ISSUE TITLE
Set up TypeScript linting

### ISSUE THREAD

**Issue by evmiguel** [bocoup/sb-util#10]
Choose a linter for the project and use it to validate changes to files

**Comment by mzgoddard** [comment]
One option would be for us to use https://prettier.io. As far as I have experienced, prettier will fix any linting errors. eslint as another option can fix a subset of its linting errors to my knowledge. I am not sure but I prettier can do it because it provides less linting customizations.

So that would be a downside, we would have to stick to most of prettiers opinions. The one default that I would change, and that prettier lets you change, is dangling commas. We should use dangling commas.
