### ISSUE TITLE
Add Scratch Version as Peer Dependencies to the and package.json and readme

### ISSUE THREAD

**Issue by nomadtechie** [bocoup/sb-util#31]
It would be great to have peer-dep requirements set to users are warned about unmet peer deps for relevant scratch projects such as `scratch-vm`.

Also, adding that information to the readme as a pre-req would be great.

**Comment by gnarf** [comment]
There is currently no dependency, peer or otherwise, on scratch-vm.

Though the deserialized format is basically borrowed from scratch-vm, the internal structures we use could still yet diverge.

Eventually I'd like to see an adapter that would let sb-util work on a "live vm source", though even  at that point we will also make an sb-util-vm package that has that peer dep to track the specific versions of vm we are supporting, putting the adapter logic in that package in order to keep the dependency chain super light on the sb-util repo itself.
